# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Pull source code
        uses: actions/checkout@master

      - name: Install requirements
        run: cat ngspicejson/config.py >> $GITHUB_ENV
      
      - name: Use the value
        run: echo "${{ env.VERSION }}"
        
      - name: Use the value
        run: echo "${{ env }}"
        
      - name: Use the value
        run: echo "${{ version }}"
        
      - name: Use the value
        run: echo "${{ env.version }}"
        
      - name: Use the value
        run: echo $version
        
      - name: Use the value
        run: echo "ASDF"
